### ISSUE TITLE
android permission automatic granted

### ISSUE THREAD

**Issue by yhl0519** [Agontuk/react-native-geolocation-service#285]
Android doesn't show permission request notification
Permissions are automatically granted.

test project:
https://github.com/yhl0519/location_test

**Comment by Agontuk** [comment]
Please provide further details about the issue and your project environment (rn version, package version, android version etc)

**Comment by cbahir** [comment]
**RN Version**: 0.64.2
**Library Version**: 5.2.0
**Tested Android Versions**: Android 7, Android 10, Android 11 (Emulator)

Ref Example Link: [https://github.com/Agontuk/react-native-geolocation-service/blob/master/example/src/App.js](url)

I have used 3 Constant of your example file:
-  hasPermissionIOS()
-  hasLocationPermission()
-  getLocation()

Configure getLocation() into useEffect to call when screen initialize.

**Current Behavior**: Not getting permission popup while screen open. And I check into app-info of My Application and their is already enabled location permission. The Fact is I never use Location related permission before in my app. then why it's already enabled?

**Expected Behavior**: When I open screen, Permission popup will come up.

- I haven't check into IOS, but in Android I checked into Multiple devices with Different Android Versions.


**AndroidManifest.xml** File
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

**Comment by Agontuk** [comment]
Does the example project behave the same way ?

**Comment by yhl0519** [comment]
yes, It only happens in your development phase, and works normally in release! thank you!
